version: '3.8'
services:
  frontend:
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    # depends_on:
    #   backend:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.insightify.description: "Next.js Frontend Service"

  backend_person_service:
    container_name: backend-person-container
    build:
      context: ./backend/Person
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.insightify.description: "Backend Person Microservice"

    #news, search, identity matching, data processing

  
