apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deployment
  labels:
    app: news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news-container
        image: CNSt3.azurecr.io/news:${COMMIT-HASH}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: Always
        env:
        - name: NEWSAPIKEY
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: newsApiKey
        - name: OPENAIAPIKEY
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: openAiApiKey
