apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deployment
  labels:
    app: news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news-container
        image: CNSt3.azurecr.io/news:${TIMESTAMP}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: Always
