name: FYP CI Pipeline
on:
  push:
    branches: ['main', 'feature/*', 'hotfix/*']

jobs:
  npm-vulnerabilities-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Vulnerability check
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Scan for frontend npm package vulnerabilities
        run: |
          npm install
          bash script/pipeline/scan_for_vulnerabilities.sh

  SAST-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Python SAST Scan
        uses: AppThreat/sast-scan-action@master
        with:
          output: reports
          type: python
      - name: Store SAST scan results
        uses: actions/upload-artifact@v4
        with:
          name: SAST-report
          path: reports

  lint-nextjs:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up lint scan
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm i
      # - name: Nextjs Lint Scan
      #   run: npm run lint
      - name: Airbnb Lint Scan
        run: npm run airbnb-lint src

  lint-fastapi:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r backend/requirements.txt
      - name: Flake8 Lint Scan
        run: |
          cd backend/api
          flake8 . --count --ignore=E203,E266,E302,E305,E402,E501,W503,F403,F401,W291,W292 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  unit-test-fastapi:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r backend/requirements.txt
      - name: Run unit tests
        run: |
          coverage run -m unittest discover backend/tests
          python -m coverage xml
      - name: Store python unit test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unittest-coverage
          path: coverage.xml

  sonarqube-scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # not sure if need anot have to see until CI is set up
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
